### ISSUE TITLE
Cannot set header information

### ISSUE THREAD

**Issue by os-jsplopes** [octokit/graphql-action#16]
Hi, i like your client for github, but i'm struggling to pass the accept parameter on header in order to use packages-preview api.
I've tried different approaches but i can't put it working.
Maybe if you put some examples how to customize the header on your documentation.

Best Regards,.

**Comment by gr2m** [comment]
Could you try to pass `with.headers` and set the value to a JSON string? Like this?

```yml
    steps:
      - uses: octokit/graphql-action@v2.x
        id: get_latest_release
        with:
          query: ...
          headers: { "accept": "application/vnd.github.corsair-preview+json" }
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
```

I haven't tried that myself, but that's what we do on https://github.com/octokit/request-action. I'm not sure if we need to adapt the action to make it work more easily.

I think we should also be able to simplify the API to do sth like this:

```yml
    steps:
      - uses: octokit/graphql-action@v2.x
        id: get_latest_release
        with:
          query: ...
          previews: corsair, elektra
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
```

But that would require some more work
