### ISSUE TITLE
Arrays in nodes or edges appear to be blank when running the action.

### ISSUE THREAD

**Issue by kevinmcct** [octokit/graphql-action#161]
When running a query using the gh api graphql call the values in arrays are visible after the query runs.  The query is written to check the ProjectV2ItemFieldIterationValue for an Issue, then have the ability to recall the value later in the action.

The issue in question is a member of a Project with a Iteration custom field.

Example using gh api graphql:
```
gh api graphql -f query='query get_story_and_iteration  {
  user(login: "kevinmcct") {
    repository(name: "GitHub-action-test") {
      issue(number: 34) {
        projectItems(first: 1) {
          nodes {
            fieldValueByName(name: "Sprint") {
              ... on ProjectV2ItemFieldIterationValue {
                title
              }
            }
          }
        }
      }
    }
  }
}' > sprint.json
```
```
cat sprint.json
{"data":{"repository":{"issue":{"title":"new issues with auto #34 12345678","projectItems":{"nodes":[{"fieldValueByName":{"title":"Sprint 2"}}]}}}}}
```

When running the same query using octokit/graphql-action@v2.2.1 in an action the query runs with no errors, but when trying to view the data returned by the query I can't see the data past the nodes [] section of the output data.

Example running octokit/graphql-action@v2.2.1:
```
Run octokit/graphql-action@v2.2.1
  with:
    query: query sprint ($owner:String!,$repo:String!,$gh_issue_number:Int!){
    user(login: $owner) {
      repository(name: $repo) {
        issue(number: $gh_issue_number) {
          projectItems(first: 1) {
            nodes {                          
              iteration:fieldValueByName(name: "Sprint") {
                ... on ProjectV2ItemFieldIterationValue {
                  title
                }
              }
            }
          }
        }
      }
    }
  }
  
    owner: kevinmcct
    repo: GitHub-action-test
    gh_issue_number: [3](https://github.com/kevinmcct/GitHub-action-test/actions/runs/3183587445/jobs/5190984944#step:2:3)[4](https://github.com/kevinmcct/GitHub-action-test/actions/runs/3183587445/jobs/5190984944#step:2:4)
  env:
    GITHUB_TOKEN: ***
query sprint ($owner:String!,$repo:String!,$gh_issue_number:Int!){
  user(login: $owner) {
    repository(name: $repo) {
      issue(number: $gh_issue_number) {
        projectItems(first: 1) {
          edges {
            node {                          
              iteration:fieldValueByName(name: "Sprint") {
                ... on ProjectV2ItemFieldIterationValue {
                  title
                }
              }
            }
          }
        }
      }
    }
  }
}

> owner: kevinmcct
> repo: GitHub-action-test
> gh_issue_number: [34](https://github.com/kevinmcct/GitHub-action-test/actions/runs/3183587445/jobs/5190984944#step:2:35)
```
```
Run echo 'Sprint Name: {
Sprint Name: {
  "user": {
    "repository": {
      "issue": {
        "projectItems": {
          "nodes": []
        }
      }
    }
  }
}
```

Am I missing some additional information when trying to recall the information or is there something strange happening in my query?

Here is the action I am using:
```
name: Advanced Sync issue to Azure DevOps work item

on:
  issues:
    types:
      [opened, edited, deleted, closed, reopened, labeled, unlabeled, assigned]
env:
  GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}

jobs:
  graphQL:
    runs-on: ubuntu-latest
    steps:
    - uses: octokit/graphql-action@v2.2.1
      id: sprint
      with:
        query: |
          query sprint ($owner:String!,$repo:String!,$gh_issue_number:Int!){
            user(login: $owner) {
              repository(name: $repo) {
                issue(number: $gh_issue_number) {
                  projectItems(first: 1) {
                    nodes {
                      fieldValueByName(name: "Sprint") {
                        ... on ProjectV2ItemFieldIterationValue {
                          title
                        }
                      }
                    }
                  }
                }
              }
            }
          }
        owner: kevinmcct
        repo: ${{ github.event.repository.name }}
        gh_issue_number: ${{ github.event.issue.number }}
    - run: "echo 'Sprint Name: ${{ steps.sprint.outputs.data }}'"
```

**Comment by oscard0m** [comment]
Hi @kevinmcct,

Thanks for reporting this issue and taking the time on giving this detailed explanation.

I tried to reproduce the bug by creating a Project V2 + associating the GitHub Issue with a GitHub Project and I'm getting output inside nodes:

```js
Success - Main echo 'Sprint Name: {
  "user": {
    "repository": {
      "issue": {
        "projectItems": {
          "nodes": [
            {
              "fieldValueByName": null
            }
          ]
        }
      }
    }
  }
}'
```
Is the repository you are working with public? If not, can you create an example repository where we can reproduce the issue?

I'm assuming the example using `gh API graphql` is running the query over the same repository, and GitHub issue number, right?

**Comment by serudda** [comment]
@kevinmcct Did you solve it? 
Same issue here, I run mmy query graphql in https://studio.apollographql.com/public/github/explorer?variant=current
And it shows me all the tree data:

![Screenshot 2023-03-18 at 4 26 26 PM](https://user-images.githubusercontent.com/10075532/226141011-ed4189b7-8526-4f84-96f4-14ef27081e3b.png)

But running the same query into my Github Action, the projectItems/nodes is []

![image](https://user-images.githubusercontent.com/10075532/226141042-ce738894-f3cd-4b72-9e76-5b2c2c20b042.png)

this is my yaml file:

``` yml
name: Send Reward to the Assignee
on:
  pull_request:
    types: [closed]
jobs:
  send-reward-to-assignee:
    runs-on: ubuntu-latest
    if: github.event.pull_request.merged == true

    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Install Node.js
        uses: actions/setup-node@v2
        with:
          node-version: '14.x'

      - name: Get Issue Number
        id: get_issue_number
        env:
          GITHUB_CONTEXT: ${{ toJson(github) }}
        run: |
          issue_number=$(echo "${{ github.event.pull_request.title }}" | grep -oE 'RS-[0-9]+' | head -1 | cut -d'-' -f2)
          echo "issue_number_int=$(echo $((issue_number)) | awk '{print int($0)}')" >> $GITHUB_OUTPUT

      - name: Get Coins from Github Issue
        uses: octokit/graphql-action@v2.x
        id: get_coins
        with:
          query: |
            query GetCoinsAndAssigneeUser($owner:String!, $repo:String!, $issue:Int!) {
              repository(owner:$owner, name:$repo) {
                issue(number:$issue) {
                  assignees(first: 10) {
                    nodes {
                      id
                      avatarUrl
                      email
                      name
                      login
                    }
                  }
                  projectItems (first: 100, includeArchived: false) {
                    nodes {
                      fieldValueByName(name: "Reward") {
                        ... on ProjectV2ItemFieldNumberValue {
                          number
                        }
                      }
                    }
                  }
                }
              }
            }
          owner: ${{ github.event.repository.owner.login }}
          repo: ${{ github.event.repository.name }}
          issue: ${{steps.get_issue_number.outputs.issue_number_int}}
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}

      - name: Set Variables
        id: vars
        run: |
          echo "${{ steps.get_coins.outputs.data }}"
          echo "github_id=${{ fromJson(steps.get_coins.outputs.data).repository.issue.assignees.nodes[0].id }}" >> $GITHUB_OUTPUT
          echo "login=${{ fromJson(steps.get_coins.outputs.data).repository.issue.assignees.nodes[0].login }}" >> $GITHUB_OUTPUT
          echo "name=${{ fromJson(steps.get_coins.outputs.data).repository.issue.assignees.nodes[0].name }}" >> $GITHUB_OUTPUT
          echo "avatar_url=${{ fromJson(steps.get_coins.outputs.data).repository.issue.assignees.nodes[0].avatarUrl }}" >> $GITHUB_OUTPUT
          echo "email=${{ fromJson(steps.get_coins.outputs.data).repository.issue.assignees.nodes[0].email }}" >> $GITHUB_OUTPUT
          echo "coins=400" >> $GITHUB_OUTPUT

      - name: Send Coins By Github Id
        uses: fjogeleit/http-request-action@v1
        id: send_coins
        with:
          url: 'https://reward-system-nextjs-wvfw-c5u2i07sw-serudda.vercel./api/trpc/user.sendCoinsByGithubId?batch=1'
          method: 'POST'
          customHeaders: '{"Content-Type": "application/json"}'
          data: '{"0":{"json":{"user":{"id":"${{ steps.vars.outputs.github_id }}","login":"${{ steps.vars.outputs.login }}","name":"${{ steps.vars.outputs.name }}","email":"${{ steps.vars.outputs.email }}","avatarUrl":"${{ steps.vars.outputs.github_id }}"},"coins":"${{ steps.vars.outputs.coins }}"}}}'

```


@oscard0m 

I have the suspicion that it has to do with the permissions of the `GITHUB_TOKEN`

Is there a way to use `PERSONAL_TOKEN` instead of `GITHUB_TOKEN`?
