### ISSUE TITLE
This action doesn't accept camelCase variables

### ISSUE THREAD

**Issue by alexrintt** [octokit/graphql-action#164]
I saw that here:

https://github.com/octokit/graphql-action/blob/6ea3f9b4f3e529207f5899d09335883ab219f386/index.js#L35-L38

We are parsing the inputs using `toLowerCase()` which results in providing the wrong query variable when executing it.

I don't know if it's expected or if it's already addressed but it is present in the latest release.

My below action fails:

```yaml
name: Delete Discussion from outside collaborators
on:
  discussion_comment: 
    types: [created]

jobs:
  job1:
    runs-on: ubuntu-latest
    if: >
      (github.event_name == 'discussion_comment') && 
      (github.event.action == 'created') &&
      (github.event.comment.user.id == github.event.discussion.user.id) &&
      (github.event.comment.body == format('{0}{1}', 'DELETE MY POST ', github.event.discussion.title))
    steps:
      - name: Delete discussion through GitHub GraphQL API
        uses: octokit/graphql-action@v2.2.1
        with:
          query: |
            mutation DeleteDiscussion($discussionId: ID!) {
              deleteDiscussion(input: { id: $discussionId }) {
                clientMutationId
              }
            }
          discussionId: ${{ github.event.discussion.node_id }}
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
```

with:

![image](https://user-images.githubusercontent.com/51419598/197214561-69f4d16d-1866-4e24-9624-aad21413f20b.png)

```shell
Error: Variable $discussionId of type ID! was provided invalid value
```

This happens because since we're providing the `discussionid` (note the lowercase) instead of `discussionId`, the actual value sent to the query var is undefined or whatever but not the value provided in the action.

The workaround is to provide declare lowercase variables in the GraphQL query string itself:

```diff
name: Delete Discussion from outside collaborators
on:
  discussion_comment: 
    types: [created]

jobs:
  job1:
    runs-on: ubuntu-latest
    if: >
      (github.event_name == 'discussion_comment') && 
      (github.event.action == 'created') &&
      (github.event.comment.user.id == github.event.discussion.user.id) &&
      (github.event.comment.body == format('{0}{1}', 'DELETE MY POST ', github.event.discussion.title))
    steps:
      - name: Delete discussion through GitHub GraphQL API
        uses: octokit/graphql-action@v2.2.1
        with:
          query: |
-            mutation DeleteDiscussion($discussionId: ID!) {
+            mutation DeleteDiscussion($discussionid: ID!) {
-              deleteDiscussion(input: { id: $discussionId }) {
+              deleteDiscussion(input: { id: $discussionid }) {
                clientMutationId
              }
            }
           # optional change, since the input will be parsed as lowercase anyways.
-          discussionId: ${{ github.event.discussion.node_id }}
+          discussionid: ${{ github.event.discussion.node_id }}
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
      - run: "The issue was deleted by the author and can't be restored anymore."
```

I'm also playing with this action less than an hour so let me know if I am missing something.

Thanks.
