### ISSUE TITLE
[BUG]: String parameters can unintentionally get parsed as numbers

### ISSUE THREAD

**Issue by MorMundHS-MA** [octokit/graphql-action#190]
### What happened?

We have an action that takes a partial git SHA and resolves it to the complete SHA of a commit using a graphql query.

``` YAML
      - name: Get full git sha
        uses: octokit/graphql-action@v2.2.23
        with:
          query: |
            query getFullCommitSha($owner: String!, $repo: String!, $sha: String!) {
              repository(owner: $owner, name: $repo) {
               object(expression: $sha) {
                  oid
                }
              }
            }
          owner: "${{ github.event.repository.owner.login }}"
          repo: "${{ github.event.repository.name }}"
          sha: "${{ steps.prior-step.outputs.partialCommitSha }}"
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
```

This works fine for most SHAs but whenever a SHA can be interpreted as number, the action fails. We first noticed this with a SHA that was an exponent number e.g. `1234e3`. For this case it was sufficient to add escaped qoutes to the SHA parameter in the YAML file i.e. `sha: "\"${{ steps.prior-step.outputs.partialCommitSha }}\""`.

However for purely numeric SHA substrings, the action still parses the string as an integer with no clearly documented way of preventing this behavior.

For now we use interpolation in the query itself, without using variables to get the correct behavior:
``` YAML
      - name: Get full git sha
        uses: octokit/graphql-action@v2.2.23
        with:
          query: |
            query getFullCommitSha {
              repository(owner: "${{ github.event.repository.owner.login }}", name: "${{ github.event.repository.name }}") {
               object(expression: "${{ steps.prior-step.outputs.partialCommitSha }}") {
                  oid
                }
              }
            }
```

### Versions

octokit/graphql-action@v2.2.23

### Relevant log output

```shell
##[debug]....Evaluating String:
##[debug]....=> 'partialCommitSha'
##[debug]..=> '05202765'
##[debug]=> '"05202765"'
##[debug]Result: '"05202765"'
Warning: Unexpected input(s) 'owner', 'repo', 'sha', valid inputs are ['query']
##[debug]Loading env
Run octokit/graphql-action@v2.2.23
  
query getFullCommitSha($owner: String!, $repo: String!, $sha: String!) {
  repository(owner: $owner, name: $repo) {
   object(expression: $sha) {
      oid
    }
  }
}
> owner: ...
> repo: ...
> sha: 5202765
##[debug]GraphqlResponseError: Request failed due to following response errors:
##[debug] - Variable $sha of type String! was provided invalid value
##[debug]    at /home/runner/work/_actions/octokit/graphql-action/v2.2.23/dist/index.js:15207:13
##[debug]    at processTicksAndRejections (node:internal/process/task_queues:96:5)
##[debug]    at async main (/home/runner/work/_actions/octokit/graphql-action/v2.2.23/dist/index.js:1057:18) {
```

### Code of Conduct

- [X] I agree to follow this project's Code of Conduct

**Comment by nickfloyd** [comment]
Hey @MorMundHS-MA great catch, and thank you for letting us know about it. ❤️ .  Is this something you might be up for tackling and submitting a PR for?  either way, we'll get it in the backlog to be prioritized and worked on.  

Thank you again for the help!

**Comment by MorMundHS-MA** [comment]
Hi @nickfloyd , thanks for the reply! I'd be up for submitting a PR, however I'm not sure what the intended behavior would be. Parsing of numbers was requested in the past (#7) which I guess introduced the problem. At the moment I have two potential ideas but neither seems optimal.

1. Attempt to support escaped quotes for numeric strings. This would be the least disruptive but feels more like a band-aid fix, since people may still run into the issue and spent a lot of time debugging it before realizing that they should put quotes around their strings.
2. A more radical solution could be having a separate `variables` input which accepts a YAML/JSON string e.g. :
  ``` YAML
      step:
          with:
            query: |
               query test($string: String!, $number: Number!) {
                 ...
               }
            variables: | 
              string:
                  value: A string
                  type: String
              number:
                  value: 1234
                  type: Number
  ``` 
  This would also get rid of the `Warning: Unexpected input(s) 'foo', 'bar', valid inputs are ['query']` warnings when using the actions, as an additional benefit.

Either way I could start setting up test cases for the exponent string and numeric string inputs all ready I guess.

**Comment by richvdh** [comment]
> A more radical solution could be having a separate variables input which accepts a YAML/JSON string e.g. :

In theory GraphQL variables can be complete objects. I wonder if it would be better just to accept raw JSON for `variables`:

```yaml
      step:
        with:
          query: |
            query test($string: String!, $number: Number!) {
              ...
            }
          variables: |
            {
              string: "A string",
              number: 1234,
              object: {
                k1: 1
              }
            }
```
